version: '3.8'

services:
  mysql_docker:
    image: mysql
    container_name: mysql_docker
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_USER
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_docker
