version: '3.8'

services:
  mysql_docker:
    image: mysql
    container_name: mysql_docker
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: projectmanager
    ports:
      - "33060:3306"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - mysql_docker
    network_mode: "host"
